/// 设置 — 双语
library;

import 'package:flutter/material.dart';
import '../main.dart';
import '../l10n.dart';
import '../p2p/signaling_client.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});
  @override State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  final _sigCtrl = TextEditingController(text: SignalingClient.cachedUrl ?? 'ws://38.22.90.80:8765');
  bool _bt = false, _expRelay = false;

  @override void dispose() { _sigCtrl.dispose(); super.dispose(); }

  @override Widget build(BuildContext context) {
    return ListenableBuilder(listenable: L10n.instance, builder: (_, __) {
    final l = L10n.instance;
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(title: const Text('⚙️ 设置 / Settings')),
      body: ListView(children: [
        // 语言
        _section(l.lang == AppLang.zh ? '🌐 语言 / Language' : '🌐 Language', [
          SwitchListTile(
            title: Text(l.lang == AppLang.zh ? '中文' : 'English'),
            subtitle: Text(l.lang == AppLang.zh ? '切换为 English' : 'Switch to 中文'),
            value: l.lang == AppLang.zh,
            onChanged: (_) { l.toggle(); },
          ),
        ]),
        // 主题
        _section(l.lang == AppLang.zh ? (isDark ? '🌙 暗色模式' : '☀️ 亮色模式') : (isDark ? '🌙 Dark Mode' : '☀️ Light Mode'), [
          SwitchListTile(
            title: Text(isDark ? (l.lang == AppLang.zh ? '暗色模式' : 'Dark Mode') : (l.lang == AppLang.zh ? '亮色模式' : 'Light Mode')),
            value: isDark,
            onChanged: (_) => SecureChatApp.of(context)?.toggleTheme(),
          ),
        ]),
        // 信令
        _section(l.lang == AppLang.zh ? '☁️ 信令服务器' : '☁️ Signaling Server', [
          Padding(padding: const EdgeInsets.all(16), child: TextField(
            controller: _sigCtrl,
            decoration: InputDecoration(
              hintText: 'ws://38.22.90.80:8765', border: const OutlineInputBorder(),
              helperText: l.lang == AppLang.zh ? '跨网络连接需要信令服务器' : 'Required for cross-network connections',
            ),
            onChanged: (v) => SignalingClient.cachedUrl = v,
          )),
        ]),
        // 实验性功能
        _section(l.lang == AppLang.zh ? '🧪 实验性功能' : '🧪 Experimental', [
          SwitchListTile(
            title: Text(l.lang == AppLang.zh ? '蓝牙发现' : 'Bluetooth Discovery'),
            subtitle: Text(l.lang == AppLang.zh ? '通过蓝牙发现附近设备（可能不稳定）' : 'Discover nearby devices via Bluetooth (unstable)'),
            value: _bt, onChanged: (v) => setState(() => _bt = v),
          ),
          SwitchListTile(
            title: Text(l.lang == AppLang.zh ? '信令中继' : 'Signaling Relay'),
            subtitle: Text(l.lang == AppLang.zh ? '消息通过信令服务器中转（跨网可靠）' : 'Relay messages through signaling server (cross-network)'),
            value: _expRelay, onChanged: (v) => setState(() => _expRelay = v),
          ),
        ]),
        // 关于
        _section(l.lang == AppLang.zh ? '💜 关于' : '💜 About', [
          const ListTile(title: Text('三彩丸子', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)), subtitle: Text('v1.1.0-beta')),
          Padding(padding: const EdgeInsets.symmetric(horizontal: 16), child: Text(
            l.lang == AppLang.zh
              ? '端到端加密私密聊天工具。\n你的消息只存在于你与对方之间，\n不经过任何服务器的存储。\n\n💻 全部代码由 AI 生成\n🧑 项目创造者 JackZhao\n\n安全 · 私密 · 开源 · 免费'
              : 'End-to-end encrypted private chat.\nYour messages exist only between you\nand your peer. No server storage.\n\n💻 All code generated by AI\n🧑 Created by JackZhao\n\nSecure · Private · Open Source · Free',
            style: const TextStyle(fontSize: 14, height: 1.6),
          )),
        ]),
      ]),
    );
    });
  }

  Widget _section(String title, List<Widget> children) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
    Padding(padding: const EdgeInsets.fromLTRB(16, 24, 16, 8), child: Text(title, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Theme.of(context).colorScheme.primary))),
    ...children, const Divider(),
  ]);
}
